version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.12
  - dependency-name: "@nuxt/image"
    versions:
    - 0.2.1
    - 0.3.0
    - 0.4.0
    - 0.4.5
  - dependency-name: core-js
    versions:
    - 3.10.2
    - 3.9.0
  - dependency-name: nuxt
    versions:
    - 2.15.0
    - 2.15.1
    - 2.15.4
  - dependency-name: "@nuxtjs/tailwindcss"
    versions:
    - 3.4.3
    - 4.0.1
    - 4.0.2
  - dependency-name: "@nuxt/content"
    versions:
    - 1.13.1
  - dependency-name: mapbox-gl
    versions:
    - 2.1.0
  - dependency-name: eslint
    versions:
    - 7.18.0
