backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: 'articles'
    label: 'Articles'
    folder: 'content/articles'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }
  - name: 'randonnees'
    label: 'Randonnées'
    folder: 'content/randonnees'
    path: '{{massif}}/{{slug}}'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Massif', name: 'massif', widget: 'select', options: ['vercors', 'bauges', 'chartreuse', 'belledonne', 'ecrins', 'vanoise', 'taillefer', 'queyras', 'devoluy'] }
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Image de couverture', name: 'img', widget: 'string', hint: 'lien cloudinary' }
      - { label: 'Légende image de couverture', name: 'caption', widget: 'string' }
      - { label: 'Lien GPX', name: 'gpx', widget: 'string', hint: 'lien en de api.monpetitsommet.fr' }
      - { label: 'Note', name: 'rating', widget: 'number', value_type: 'int', min: 0, max: 5, step: 1 }
      - { label: 'Distance', name: 'distance', widget: 'number', value_type: 'float', step: 0.01 }
      - { label: 'Dénivelé +', name: 'elevation', widget: 'number', value_type: 'float', step: 0.01 }
      - { label: 'Durée +', name: 'duration', widget: 'string', hint: 'Durée en jours' }
      - { label: 'Difficulté', name: 'difficulty', widget: 'string', hint: 'ex: T1, T2 ...' }
      - { label: 'Présence eau', name: 'water', widget: 'boolean' }
      - { label: 'Utilisation tente', name: 'tent', widget: 'boolean' }
      - { label: 'Ville départ', name: 'from', widget: 'string' }
      - { label: 'Ville arrivée', name: 'to', widget: 'string' }
      - {
          label: 'Sections', name: 'sections', widget: 'list', label_singular: 'Ajouter une section', summary: '{{fields.label}}', fields:
            - { label: 'Titre', name: 'title', widget: 'string' }
            - { label: 'Nom début section', name: 'from', widget: 'number', step: 1 }
            - { label: 'Nom fin section', name: 'to', widget: 'number', step: 1 }
        }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }
  - name: 'refuges'
    label: 'Refuges'
    folder: 'content/refuges'
    path: '{{massif}}/{{slug}}'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Massif', name: 'massif', widget: 'string' }
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }
