backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: 'articles'
    label: 'Articles'
    folder: 'content/articles'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }
  - name: 'randonnees'
    label: 'Randonnées'
    folder: 'content/randonnees'
    path: '{{massif}}/{{slug}}'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Massif', name: 'massif', widget: 'select', options: ['vercors', 'bauges', 'chartreuse', 'belledonne', 'ecrins', 'vanoise', 'taillefer', 'queyras', 'devoluy'] }
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Image de couverture', name: 'img', widget: 'string', hint: 'lien cloudinary' }
      - { label: 'Légende image de couverture', name: 'caption', widget: 'string' }
      - { label: 'Lien GPX', name: 'gpx', widget: 'string', hint: 'lien de api.monpetitsommet.fr' }
      - { label: 'Note', name: 'rating', widget: 'number', value_type: 'int', min: 0, max: 5, step: 1 }
      - { label: 'Distance', name: 'distance', widget: 'number', value_type: 'float', step: 0.01 }
      - { label: 'Dénivelé +', name: 'elevation', widget: 'number', value_type: 'float', step: 0.01 }
      - { label: 'Durée +', name: 'duration', widget: 'string', hint: 'Durée en jours' }
      - { label: 'Difficulté', name: 'difficulty', widget: 'string', hint: 'ex: T1, T2 ...' }
      - { label: 'Présence eau', name: 'water', widget: 'boolean' }
      - { label: 'Utilisation tente', name: 'tent', widget: 'boolean' }
      - { label: 'Ville départ', name: 'from', widget: 'string' }
      - { label: 'Ville arrivée', name: 'to', widget: 'string' }
      - {
          label: 'Sections', name: 'sections', widget: 'list', label_singular: 'section', summary: '{{fields.title}}', fields: [
            { label: 'Titre', name: 'title', widget: 'string' },
            { label: 'Index début section', name: 'from', required: false, widget: 'number', step: 1 },
            { label: 'Index fin section', name: 'to', required: false, widget: 'number', step: 1 }
          ]
        }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }
  - name: 'refuges'
    label: 'Refuges'
    folder: 'content/refuges'
    path: '{{massif}}/{{slug}}'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Massif', name: 'massif', widget: 'select', options: ['vercors', 'bauges', 'chartreuse', 'belledonne', 'ecrins', 'vanoise', 'taillefer', 'queyras', 'devoluy'] }
      - { label: 'Nom', name: 'name', widget: 'string' }
      - { label: 'Type', name: 'type', widget: 'select', options: ['cabane non gardée', 'gîte d'étape', 'refuge gardé'] }
      - { label: 'Image de couverture', name: 'img', widget: 'string' }
      - { label: 'Nombre de lits', name: 'beds', widget: 'number', value_type: 'int', min: 0, step: 1 }
      - { label: 'Altitude', name: 'altitude', widget: 'number', value_type: 'int' }
      - { label: 'Longitude', name: 'longitude', widget: 'number', value_type: 'float' }
      - { label: 'Latitude', name: 'latitude', widget: 'number', value_type: 'float' }
      - { label: 'Eau à proximité', name: 'water', widget: 'boolean' }
      - { label: 'Présence de toilettes', name: 'toilets', widget: 'boolean' }
      - { label: 'Bois à proximité', name: 'wood', widget: 'boolean' }
      - { label: 'Présence poêle', name: 'stove', widget: 'boolean' }
      - { label: 'Nombre de matelas', name: 'matresses', widget: 'number', value_type: 'int', min: 0, step: 1 }
      - { label: 'Présence de couvertures', name: 'blankets', widget: 'boolean' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }
