backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: 'articles'
    label: 'Articles'
    folder: 'content/articles'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Date de publication', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }
  - name: 'randonnees'
    label: 'Randonnées'
    folder: 'content/randonnees'
    path: '{{massif}}/{{slug}}'
    nested:
      depth: 100
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Massif', name: 'massif', widget: 'string' }
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Date de publication', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }
  - name: 'refuges'
    label: 'Refuges'
    folder: 'content/refuges'
    path: '{{massif}}/{{slug}}'
    nested:
      depth: 100
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Massif', name: 'massif', widget: 'string' }
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Date de publication', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }
